### ISSUE TITLE
Don't work and try on one fan only

### ISSUE THREAD

**Issue by Elikill58** [nmtitov/redfan#2]
Hi,

I just install redfan as write in installation instruction, and I don't any issue : well installed, and well running.

Now, when I do `redfan` :
- Even with "CTRL + C" I always receive print log
- Print log say that it can find folder after `/sys/class/drm/card1/device/` (so, can't find `hwmon`)

How can I fix both ?
And such as I receive log message for only one fan, it doesn't manage all others fans ?

**Comment by nmtitov** [comment]
@Elikill58 sorry to hear that, I don't have my Ubuntu system anymore so I can't really reproduce issues you mentioned

**Comment by Elikill58** [comment]
Ok so how can we do ?
Also, can you make change to check for all cards and all fans ? Because I have 2 cards, and over 6 fans. I have GreenWithEnvy which manage one of two card, but the other isn't managed :/

**Comment by nmtitov** [comment]
I don't do mining anymore so I can't offer any support on this code, unfortunately. Feel free to fork & modify the code though.

This is the only important part: https://github.com/nmtitov/redfan/blob/main/redfan
You can add more lines like:

```
echo 0 > /sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable;
```

All you need is to find the pseudo-file interface of your card (`card1` in my case, installed in PCI-E slot 1) and then `echo 0` to its `pwm1_enable` "file" value.

I think you can find existing interfaces by calling something like this in the terminal:

```
cat /sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable
```

If you see a value printed, it means you have found your card & fan. If you get an error, then try another card number or another `hwmon` number or `pmw` number.

**Comment by Elikill58** [comment]
Ok thanks, I will make a PR :p
Just, how to test my program ? I just have to do `./redfan` ?

**Comment by nmtitov** [comment]
> Ok thanks, I will make a PR :p
> Just, how to test my program ? I just have to do `./redfan` ?

Yes 👍 

You can also just enter 

```
echo 0 > /sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable;
```

You should hear a change in the way how fans work but it will be reset by the driver in about 1-2 seconds

**Comment by Elikill58** [comment]
The issue is that for me, this folder doesn't exist.
So, I just try to find where is it, and it seems to be here:
`/sys/devices/platform/nct6775.2592/hwmon/hwmon0`

So, I tried to do like `echo 0 > /sys/devices/platform/nct6775.2592/hwmon/hwmon0/pwm1_enable`. The given file was at 5, now it's at 0, but nothing change ... Maybe it's not the good file, or I forgot something ?

**Comment by nmtitov** [comment]
Have you installed AMD drivers?

**Comment by Elikill58** [comment]
I only have NVIDIA drivers because I have two nvidia graphic cards

**Comment by nmtitov** [comment]
Oh wow. This project won’t help you, it’s purpose is only to fix a bug in AMD drivers for Ubuntu 20.04. That’s why it’s called “red” fan 😆

**Comment by Elikill58** [comment]
Oh ok :/
Thanks you for all informations !

**Comment by nmtitov** [comment]
Try to experiment though, maybe you could find a fix by using the same strategy

**Comment by Elikill58** [comment]
That's what I'm trying to.
But i don't know where are the required files

**Comment by nmtitov** [comment]
Looks like the NVIDIA driver does mapping in a different way (but the idea should be the same because Linux philosophy is "everything is a file"). Unfortunately, I have no experience with Nvidia cards :(

**Comment by Elikill58** [comment]
Ok, that's a good news so !
No problem x)
Will you accept if a day I make a PR to add nvidia support ? :)

**Comment by nmtitov** [comment]
Sure 👍
