### ISSUE TITLE
card0/card1

### ISSUE THREAD

**Issue by antiwesley** [nmtitov/redfan#3]
I couldn't get it to run at first, getting

Mar 10 20:45:44 Tux redfan[5918]: /usr/bin/redfan: line 4: /sys/class/drm/card1/device/hwmon/hwmon1/pwm1_enable: No such file or directory

as the error.

After manually checking my directory structure in the line in redfan, I discovered that my "card1" is actually "card0" 

so I changed this in the script after stopping the service, and saved the new location, and restarted the service, and VOILA! 
My fan is now running without stopping. :)

**Comment by antiwesley** [comment]
and now, a couple hours later, 

`sudo systemctl stop redfan`

stops the service, 

```
sudo systemctl status redfan
● redfan.service - Force disable PWM for AMD card0 device
     Loaded: loaded (/etc/systemd/system/redfan.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2022-03-10 22:58:46 CST; 17s ago
   Main PID: 6343 (code=killed, signal=TERM)

Mar 10 20:46:21 Tux systemd[1]: Starting Force disable PWM for AMD card0 device...
Mar 10 20:46:21 Tux systemd[1]: Started Force disable PWM for AMD card0 device.
Mar 10 22:58:46 Tux systemd[1]: Stopping Force disable PWM for AMD card0 device...
Mar 10 22:58:46 Tux systemd[1]: redfan.service: Succeeded.
Mar 10 22:58:46 Tux systemd[1]: Stopped Force disable PWM for AMD card0 device.

```

The service is stopped, but the fan is still running. :(

Mint 20.3
XFX RX 580
5.15.27-xanmod1

**Comment by nmtitov** [comment]
Hey, sorry for the late reply. Unfortunately I don't have Linux box anymore. But looks like echo works as intended for you? What if you "manually" stop fans by setting the value directly?
